# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.


[[main]]
  name = "Home"
  pageref = "/"
  weight = 1


[[main]]
  name = "CV"
  pageRef = "about"
  weight = 10



[[main]]
  name = "Research"
  pageRef = "research"
  weight = 20


[[main]]
  name = "Overview"
  parent = "Research"
  pageRef = "research"
  weight = 20


[[main]]
  name = "Teaching and Notes"
  pageRef = "teaching"
  weight = 30


[[main]]
  name = "Music"
  pageRef = "music"
  weight = 40

#[[main]]
#  name = "Transcriptions"
#  parent = "Music"
#  pageRef = "music_overview"
#  weight = 5

#[[main]]
#  name = "Transcriptions"
#  parent = "Music"
#  pageRef = "transcriptions"
#  weight = 5



[[main]]
  name = "Google Scholar"
  parent = "Research"
  url = "https://scholar.google.com/citations?&user=EIR50qkAAAAJ"
  weight = 50

[[main]]
  name = "arXiv"
  parent = "Research"
  url = "https://arxiv.org/a/frazier_g_1.html"
  weight = 50



[[main]]
  name = "Orcid ID"
  parent = "Research"
  url = "https://orcid.org/0000-0002-3707-2118"
  weight = 50




#[[main]]
#  name = "Blog"
#  pageRef = "posts"
#  weight = 10

#[[main]]
#  name = "Parent"
#  weight = 20

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
